In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('agua_prata_raw.csv')
df.head(10)

,codigo_stn,local_monitoramento,ano,tipo_corpo_agua,estado,temperatura_min_c,temperatura_max_c,oxigenio_dissolvido_min,oxigenio_dissolvido_max,ph_min,...,bod_min_mg_l,bod_max_mg_l,nitrato_min_mg_l,nitrato_max_mg_l,coliformes_fecais_min,coliformes_fecais_max,coliformes_totais_min,coliformes_totais_max,fecal_min,fecal_max
0,4085,"RIVER JUMAR AT BIT MESRA, RANCHI",2022,RIVER,JHARKHAND,12.0,29.0,3.3,5.2,6.5,...,2,2.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2396,RIVER JUMAR AT KANKE DAM,2022,RIVER,JHARKHAND,12.0,26.0,5.9,7.2,7.5,...,1.9,3.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2401,RIVER AJAY AT MASANJORE DAM,2022,RIVER,JHARKHAND,17.0,36.0,5.8,6.6,7.5,...,1.3,1.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3554,"RIVER KONAR NEAR SWANG COAL WASHERY, BOKARO",2022,RIVER,JHARKHAND,19.0,34.0,7.4,7.8,7.3,...,1.8,2.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2390,RIVER KONAR AT TENUGHAT DAM,2022,RIVER,JHARKHAND,16.0,33.0,7.4,8.0,7.4,...,1.3,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,4000,RIVER GARGA NEAR TELMUCHO BRIDGE,2022,RIVER,JHARKHAND,15.0,30.0,6.5,7.5,7.2,...,2.2,3.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2381,RIVER BOKARO AT ZARANGDIH BRIDGE,2022,RIVER,JHARKHAND,18.5,33.5,7.3,8.1,7.0,...,1.6,2.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1034,"RIVER SANKH AT BOLBA, JHARKHAND",2022,RIVER,JHARKHAND,12.0,27.0,7.8,8.5,7.3,...,1.1,1.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2392,RIVER BARAKAR AT MAITHAN DAM,2022,RIVER,JHARKHAND,13.0,26.0,7.3,7.8,7.4,...,1.3,2.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,3555,"RIVER DAMODAR NEAR ZARANGDIH BRIDGE, BOKARO",2022,RIVER,JHARKHAND,18.0,33.0,7.5,8.7,7.4,...,1.8,2.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.columns

Index(['codigo_stn', 'local_monitoramento', 'ano', 'tipo_corpo_agua', 'estado',
       'temperatura_min_c', 'temperatura_max_c', 'oxigenio_dissolvido_min',
       'oxigenio_dissolvido_max', 'ph_min', 'ph_max', 'condutividade_min',
       'condutividade_max', 'bod_min_mg_l', 'bod_max_mg_l', 'nitrato_min_mg_l',
       'nitrato_max_mg_l', 'coliformes_fecais_min', 'coliformes_fecais_max',
       'coliformes_totais_min', 'coliformes_totais_max', 'fecal_min',
       'fecal_max'],
      dtype='object')

In [9]:
colunas_para_converter = ['condutividade_min', 'bod_min_mg_l']

for coluna in colunas_para_converter:
    if coluna in df.columns:
        df[coluna] = pd.to_numeric(df[coluna], errors='coerce')

# Verificar os tipos de dados novamente
print("Tipos de dados apÃ³s conversÃ£o:")
print(df.dtypes)

Tipos de dados apÃ³s conversÃ£o:
codigo_stn                     int64
local_monitoramento           object
ano                            int64
tipo_corpo_agua               object
estado                        object
temperatura_min_c            float64
temperatura_max_c            float64
oxigenio_dissolvido_min      float64
oxigenio_dissolvido_max      float64
ph_min                       float64
ph_max                       float64
condutividade_min            float64
condutividade_max            float64
bod_min_mg_l                 float64
bod_max_mg_l                 float64
nitrato_min_mg_l             float64
nitrato_max_mg_l             float64
coliformes_fecais_min        float64
coliformes_fecais_max        float64
coliformes_totais_min        float64
coliformes_totais_max        float64
fecal_min                    float64
fecal_max                    float64
temperatura_media_c          float64
oxigenio_dissolvido_medio    float64
ph_medio                     float64
condutividade_media          float64
dtype: object

In [10]:
def adicionar_medias_seguras(df):
    """
    Adiciona colunas de mÃ©dia apenas quando ambos valores (min e max) estÃ£o disponÃ­veis
    """
    # ParÃ¢metros fÃ­sico-quÃ­micos (mÃ©dia aritmÃ©tica)
    parametros_aritmeticos = {
        'temperatura': ('temperatura_min_c', 'temperatura_max_c', 'temperatura_media_c'),
        'oxigenio_dissolvido': ('oxigenio_dissolvido_min', 'oxigenio_dissolvido_max', 'oxigenio_dissolvido_medio'),
        'ph': ('ph_min', 'ph_max', 'ph_medio'),
        'condutividade': ('condutividade_min', 'condutividade_max', 'condutividade_media'),
        'bod': ('bod_min_mg_l', 'bod_max_mg_l', 'bod_medio_mg_l'),
        'nitrato': ('nitrato_min_mg_l', 'nitrato_max_mg_l', 'nitrato_medio_mg_l')
    }
    
    for param, (min_col, max_col, media_col) in parametros_aritmeticos.items():
        if min_col in df.columns and max_col in df.columns:
            mask = df[min_col].notna() & df[max_col].notna()
            df[media_col] = np.nan  # Inicializar com NaN
            df.loc[mask, media_col] = (df.loc[mask, min_col] + df.loc[mask, max_col]) / 2
    
    # ParÃ¢metros microbiolÃ³gicos (mÃ©dia geomÃ©trica - mais apropriada)
    parametros_geometricos = {
        'coliformes_fecais': ('coliformes_fecais_min', 'coliformes_fecais_max', 'coliformes_fecais_medio'),
        'coliformes_totais': ('coliformes_totais_min', 'coliformes_totais_max', 'coliformes_totais_medio'),
        'fecal': ('fecal_min', 'fecal_max', 'fecal_medio')
    }
    
    for param, (min_col, max_col, media_col) in parametros_geometricos.items():
        if min_col in df.columns and max_col in df.columns:
            mask = df[min_col].notna() & df[max_col].notna()
            df[media_col] = np.nan  # Inicializar com NaN
            # Calcular mÃ©dia geomÃ©trica apenas onde ambos valores sÃ£o positivos
            mask_positivos = mask & (df[min_col] > 0) & (df[max_col] > 0)
            df.loc[mask_positivos, media_col] = np.sqrt(df.loc[mask_positivos, min_col] * df.loc[mask_positivos, max_col])
    
    return df

# Aplicar a funÃ§Ã£o para calcular mÃ©dias
df = adicionar_medias_seguras(df)

# Verificar resultados
print("\nPrimeiras linhas com mÃ©dias calculadas:")
print(df[['local_monitoramento', 'ano', 'temperatura_media_c', 'ph_medio', 'coliformes_fecais_medio']].head())

# EstatÃ­sticas de completude
print("\nCompletude dos dados apÃ³s cÃ¡lculo de mÃ©dias:")
colunas_media = [col for col in df.columns if 'medio' in col or 'media' in col]
for col in colunas_media:
    if col in df.columns:
        total = len(df)
        na_count = df[col].isna().sum()
        percent_na = (na_count / total) * 100
        print(f"{col}: {total - na_count}/{total} ({100 - percent_na:.1f}%) preenchidos")

# AnÃ¡lise por tipo de corpo d'Ã¡gua
if 'tipo_corpo_agua' in df.columns:
    print("\nCompletude por tipo de corpo d'Ã¡gua:")
    for tipo in df['tipo_corpo_agua'].unique():
        subset = df[df['tipo_corpo_agua'] == tipo]
        print(f"\n{tipo}:")
        for col in ['temperatura_media_c', 'ph_medio', 'coliformes_fecais_medio']:
            if col in df.columns:
                completude = subset[col].notna().mean() * 100
                print(f"  {col}: {completude:.1f}%")

# Salvar o dataset com as mÃ©dias
df.to_csv('aguaPrataMediasRaw.csv', index=False)
print("\nDataset salvo como 'aguaPrataMediasRaw.csv'")

Primeiras linhas com mÃ©dias calculadas:
                           local_monitoramento   ano  temperatura_media_c  \
0             RIVER JUMAR AT BIT MESRA, RANCHI  2022                 20.5
1                     RIVER JUMAR AT KANKE DAM  2022                 19.0
2                  RIVER AJAY AT MASANJORE DAM  2022                 26.5
3  RIVER KONAR NEAR SWANG COAL WASHERY, BOKARO  2022                 26.5
4                  RIVER KONAR AT TENUGHAT DAM  2022                 24.5

   ph_medio  coliformes_fecais_medio
0      6.55                      NaN
1      7.55                      NaN
2      7.65                      NaN
3      7.45                      NaN
4      7.60                      NaN

Completude dos dados apÃ³s cÃ¡lculo de mÃ©dias:
temperatura_media_c: 192/194 (99.0%) preenchidos
oxigenio_dissolvido_medio: 192/194 (99.0%) preenchidos
ph_medio: 194/194 (100.0%) preenchidos
condutividade_media: 180/194 (92.8%) preenchidos
bod_medio_mg_l: 170/194 (87.6%) preenchidos
nitrato_medio_mg_l: 179/194 (92.3%) preenchidos
coliformes_fecais_medio: 178/194 (91.8%) preenchidos
coliformes_totais_medio: 179/194 (92.3%) preenchidos
fecal_medio: 66/194 (34.0%) preenchidos

Completude por tipo de corpo d'Ã¡gua:

RIVER:
  temperatura_media_c: 100.0%
  ph_medio: 100.0%
  coliformes_fecais_medio: 74.0%

MARINE:
  temperatura_media_c: 100.0%
  ph_medio: 100.0%
  coliformes_fecais_medio: 100.0%

BEACH:
  temperatura_media_c: 100.0%
  ph_medio: 100.0%
  coliformes_fecais_medio: 100.0%

SEA:
  temperatura_media_c: 100.0%
  ph_medio: 100.0%
  coliformes_fecais_medio: 100.0%

CANAL:
  temperatura_media_c: 91.7%
  ph_medio: 100.0%
  coliformes_fecais_medio: 87.5%

LAKE:
  temperatura_media_c: 100.0%
  ph_medio: 100.0%
  coliformes_fecais_medio: 100.0%

POND:
  temperatura_media_c: 100.0%
  ph_medio: 100.0%
  coliformes_fecais_medio: 100.0%

CREEK:
  temperatura_media_c: 100.0%
  ph_medio: 100.0%
  coliformes_fecais_medio: 100.0%

DRAIN:
  temperatura_media_c: 100.0%
  ph_medio: 100.0%
  coliformes_fecais_medio: 100.0%

WATER TREATMENT PLANT (RAW WATER):
  temperatura_media_c: 100.0%
  ph_medio: 100.0%
  coliformes_fecais_medio: 100.0%

STP:
  temperatura_media_c: 100.0%
  ph_medio: 100.0%
  coliformes_fecais_medio: 100.0%

Dataset salvo como 'aguaPrataMediasRaw.csv'

In [12]:
df_medias = pd.read_csv('aguaPrataMediasRaw.csv')
df_medias.head(50)

,codigo_stn,local_monitoramento,ano,tipo_corpo_agua,estado,temperatura_min_c,temperatura_max_c,oxigenio_dissolvido_min,oxigenio_dissolvido_max,ph_min,...,fecal_max,temperatura_media_c,oxigenio_dissolvido_medio,ph_medio,condutividade_media,bod_medio_mg_l,nitrato_medio_mg_l,coliformes_fecais_medio,coliformes_totais_medio,fecal_medio
0,4085,"RIVER JUMAR AT BIT MESRA, RANCHI",2022,RIVER,JHARKHAND,12.0,29.0,3.3,5.2,6.50,...,NaN,20.50,4.25,6.550,NaN,2.45,NaN,NaN,NaN,NaN
1,2396,RIVER JUMAR AT KANKE DAM,2022,RIVER,JHARKHAND,12.0,26.0,5.9,7.2,7.50,...,NaN,19.00,6.55,7.550,NaN,2.55,NaN,NaN,NaN,NaN
2,2401,RIVER AJAY AT MASANJORE DAM,2022,RIVER,JHARKHAND,17.0,36.0,5.8,6.6,7.50,...,NaN,26.50,6.20,7.650,206.0,1.45,NaN,NaN,NaN,NaN
3,3554,"RIVER KONAR NEAR SWANG COAL WASHERY, BOKARO",2022,RIVER,JHARKHAND,19.0,34.0,7.4,7.8,7.30,...,NaN,26.50,7.60,7.450,NaN,2.25,NaN,NaN,NaN,NaN
4,2390,RIVER KONAR AT TENUGHAT DAM,2022,RIVER,JHARKHAND,16.0,33.0,7.4,8.0,7.40,...,NaN,24.50,7.70,7.600,NaN,1.65,NaN,NaN,NaN,NaN
5,4000,RIVER GARGA NEAR TELMUCHO BRIDGE,2022,RIVER,JHARKHAND,15.0,30.0,6.5,7.5,7.20,...,NaN,22.50,7.00,7.350,NaN,2.90,NaN,NaN,NaN,NaN
6,2381,RIVER BOKARO AT ZARANGDIH BRIDGE,2022,RIVER,JHARKHAND,18.5,33.5,7.3,8.1,7.00,...,NaN,26.00,7.70,7.300,NaN,2.20,NaN,NaN,NaN,NaN
7,1034,"RIVER SANKH AT BOLBA, JHARKHAND",2022,RIVER,JHARKHAND,12.0,27.0,7.8,8.5,7.30,...,NaN,19.50,8.15,7.400,NaN,1.45,NaN,NaN,NaN,NaN
8,2392,RIVER BARAKAR AT MAITHAN DAM,2022,RIVER,JHARKHAND,13.0,26.0,7.3,7.8,7.40,...,NaN,19.50,7.55,7.500,NaN,1.80,NaN,NaN,NaN,NaN
9,3555,"RIVER DAMODAR NEAR ZARANGDIH BRIDGE, BOKARO",2022,RIVER,JHARKHAND,18.0,33.0,7.5,8.7,7.40,...,NaN,25.50,8.10,7.500,NaN,2.25,NaN,NaN,NaN,NaN
10,4083,"RIVER DAMODAR NEAR ROHINI PROJECT, NK AREA, PO...",2022,RIVER,JHARKHAND,14.0,26.0,6.7,8.5,6.60,...,NaN,20.00,7.60,7.300,NaN,2.25,NaN,NaN,NaN,NaN
11,3553,RIVER DAMODAR NEAR TELMUCHO BRIDGE,2022,RIVER,JHARKHAND,14.5,30.0,7.3,8.5,7.40,...,NaN,22.25,7.90,7.550,NaN,2.85,NaN,NaN,NaN,NaN
12,1510,RIVER TONS AT TIUNI (HIMACHAL PRADESH/UTTRA KH...,2022,RIVER,HIMACHAL PRADESH,8.0,24.0,7.1,9.0,7.52,...,2.0,16.00,8.05,7.830,527.5,NaN,1.135,8.124038,84.711274,NaN
13,30023,RIVER TONS AT HARIPUR (U.K.),2022,RIVER,UTTARAKHAND,14.0,23.5,8.7,9.4,8.10,...,NaN,18.75,9.05,8.300,224.0,NaN,0.420,289.827535,1013.410085,NaN
14,4027,RIVER GIRI D/S RAJGARH TOWN,2022,RIVER,HIMACHAL PRADESH,21.0,26.0,7.5,8.3,7.55,...,NaN,23.50,7.90,7.910,417.0,NaN,0.755,32.249031,165.227116,NaN
15,4028,"RIVER GIRI D/S KALGIDHAR TRUST, BARU SAHIB",2022,RIVER,HIMACHAL PRADESH,20.0,27.0,7.4,8.2,7.79,...,NaN,23.50,7.80,8.020,481.0,NaN,0.775,31.843367,190.787840,NaN
16,4427,RIVER GIRI U/S CHAILLA,2022,RIVER,HIMACHAL PRADESH,7.0,23.0,7.0,8.6,7.23,...,NaN,15.00,7.80,7.705,807.0,NaN,1.365,8.246211,104.307238,NaN
17,2621,RIVER GIRI AT D/S YASHWANT NAGAR AFTER CONF. W...,2022,RIVER,HIMACHAL PRADESH,8.0,16.0,6.9,8.6,7.54,...,NaN,12.00,7.75,7.920,413.5,NaN,6.565,56.568542,203.960781,NaN
18,3876,RIVER GIRI AFTER CONFLUENCE OF ASHWANI RIVER A...,2022,RIVER,HIMACHAL PRADESH,7.0,18.0,7.5,8.9,7.54,...,NaN,12.50,8.20,8.010,457.0,NaN,4.190,12.569805,183.303028,NaN
19,2622,RIVER GIRI AT U/S CCI MINES AT VILLAGE NADI,2022,RIVER,HIMACHAL PRADESH,20.0,27.0,6.9,8.2,7.77,...,NaN,23.50,7.55,8.045,694.5,NaN,0.585,20.712315,82.462113,NaN
20,2623,RIVER GIRI D/S SATAUN,2022,RIVER,HIMACHAL PRADESH,19.0,27.0,7.4,8.1,7.64,...,NaN,23.00,7.75,7.965,699.5,NaN,0.660,23.366643,93.808315,NaN
21,3877,RIVER GIRI U/S LWSS AT SAINJ,2022,RIVER,HIMACHAL PRADESH,8.0,24.0,6.8,8.5,7.38,...,NaN,16.00,7.65,7.755,830.5,NaN,1.595,12.489996,149.666295,NaN
22,3878,RIVER GIRI D/S LWSS AT SAINJ,2022,RIVER,HIMACHAL PRADESH,8.0,23.0,6.9,8.5,7.37,...,NaN,15.50,7.70,7.770,830.5,NaN,2.945,15.588457,164.924225,NaN
23,3860,"RIVER GIRI D/S CEMENT CORPORATION OF INDIA, RA...",2022,RIVER,HIMACHAL PRADESH,19.0,26.0,7.4,8.0,7.60,...,NaN,22.50,7.70,7.880,638.5,NaN,0.615,23.685439,88.430764,NaN
24,1614,"RIVER BETWA NEAR WATER SUPPLY INTAKE WELL , VI...",2022,RIVER,MADHYA PRADESH,17.0,32.0,4.7,12.4,6.96,...,NaN,24.50,8.55,7.605,429.5,3.20,6.660,14.491377,204.939015,NaN
25,2107,"RIVER BETWA AT U/S AT MAHUTA GHAT, AGASOD, BINA",2022,RIVER,MADHYA PRADESH,21.0,31.0,6.0,7.5,7.32,...,NaN,26.00,6.75,7.770,383.0,1.45,1.290,3.346640,46.184413,NaN
26,2108,"RIVER BETWA AT M/S J.P. THERMAL POWER, BINA",2022,RIVER,MADHYA PRADESH,21.0,31.0,6.1,7.8,7.36,...,NaN,26.00,6.95,7.840,391.0,1.50,1.225,2.000000,40.472213,NaN
27,2124,"RIVER BETWA AT CHARANTIRGHAT, VIDISHA",2022,RIVER,MADHYA PRADESH,5.0,32.0,5.0,13.6,7.32,...,NaN,18.50,9.30,8.090,610.0,10.80,9.895,28.982753,438.178046,NaN
28,2125,RIVER BETWA D/S AFTER MIXING OF RIVER BAIS AT ...,2022,RIVER,MADHYA PRADESH,18.0,32.0,5.5,13.3,7.08,...,NaN,25.00,9.40,7.675,624.0,9.15,9.650,31.937439,489.897949,NaN
29,3832,RIVER BETWA AT U/S NEAR ROAD BRIDGE ORCHHA,2022,RIVER,MADHYA PRADESH,22.0,30.0,6.6,7.5,7.28,...,NaN,26.00,7.05,7.830,365.5,1.60,0.425,NaN,42.988371,NaN
30,30080,"RIVER BETWA AT KANJIA ROAD BRIDGE, KANJIA DIST...",2022,RIVER,MADHYA PRADESH,21.4,32.6,7.9,10.2,7.83,...,NaN,27.00,9.05,7.985,392.0,2.45,1.110,6633.249581,59623.820743,NaN
31,2953,RIVER KALI SINDH AT ANICUT OF M/S CFCL GADEPAN...,2022,RIVER,RAJASTHAN,21.0,34.0,3.7,5.6,7.98,...,38.0,27.50,4.65,8.220,599.0,1.70,1.725,52.649786,128.452326,29.563491
32,2956,"RIVER KALI SINDH AT BAROD ROAD BRIDGE, KOTA, R...",2022,RIVER,RAJASTHAN,22.0,34.0,3.7,5.1,8.15,...,25.0,28.00,4.40,8.355,965.0,1.65,2.340,43.954522,115.931014,18.708287
33,2951,"RIVER BANAS BISULPUR DAM, TONK, RAJASTHAN",2022,RIVER,RAJASTHAN,17.0,32.0,3.7,6.2,8.10,...,32.0,24.50,4.95,8.325,672.0,1.60,2.135,73.416619,175.499288,23.323808
34,2952,"RIVER NEAR NEWTA DAM,JAIPUR,RAJSTHAN",2022,RIVER,RAJASTHAN,18.0,31.0,1.6,2.9,7.97,...,NaN,24.50,2.25,8.395,2479.0,4.35,4.570,176.635217,481.871352,NaN
35,2955,RIVER CHAMBAL ENTERING IN RAJASTHAN AT GANDHI ...,2022,RIVER,RAJASTHAN,17.0,31.0,5.0,6.6,7.10,...,29.0,24.00,5.80,7.740,506.0,2.35,2.315,112.249722,242.487113,24.677925
36,3309,"RIVER CHAMBAL AT TAL VILLAGE NEAR BRIDGE, UJJAIN",2022,RIVER,MADHYA PRADESH,22.0,30.0,6.4,7.7,7.26,...,2.0,26.00,7.05,7.655,1124.5,4.00,1.640,74.296702,277.128129,2.000000
37,4349,"SEA WATER, BAY OF BENGAL, AFTER CONFLUENCE OF ...",2022,MARINE,ANDHRA PRADESH,21.0,30.0,5.2,7.2,7.40,...,NaN,25.50,6.20,7.900,35550.0,1.85,0.850,4.582576,75.894664,NaN
38,4352,"SEA WAER BAY OF BENGAL, AFTER CONFLUENCE OF MA...",2022,MARINE,ANDHRA PRADESH,25.0,28.0,5.2,6.6,7.70,...,NaN,26.50,5.90,8.100,44300.0,2.10,0.600,5.744563,90.498619,NaN
39,4357,"RUSHIKONDA BEACH,VISAKHAPATNAM",2022,BEACH,ANDHRA PRADESH,25.0,29.0,4.8,7.0,7.70,...,NaN,27.00,5.90,8.100,43700.0,2.05,0.725,6.480741,76.485293,NaN
40,4361,"SEA WATER BAY BENGAL, UPPADA BEACH ROAD, KAKINADA",2022,BEACH,ANDHRA PRADESH,25.0,28.0,4.5,7.9,7.80,...,NaN,26.50,6.20,8.150,28100.0,2.50,0.870,7.745967,84.852814,NaN
41,4362,"SEA WATER, BAY OF BENGAL NEAR DEEP WATER PORT,...",2022,SEA,ANDHRA PRADESH,25.0,27.0,5.3,8.0,7.40,...,NaN,26.00,6.65,7.900,25580.5,3.05,2.070,9.591663,185.741756,NaN
42,4363,SEA WATER BAY OF BENGAL NEAR KUMBHABHISHEKAM T...,2022,SEA,ANDHRA PRADESH,24.0,26.0,5.7,7.5,7.10,...,NaN,25.00,6.60,7.650,23740.5,2.50,2.585,7.937254,171.580885,NaN
43,4371,"SEA WATER, BAY OF BENGAL AFTER CONFLUENCE OF R...",2022,MARINE,ANDHRA PRADESH,22.0,30.0,5.1,8.0,7.80,...,NaN,26.00,6.55,8.100,29400.0,1.65,0.765,6.480741,76.681158,NaN
44,4378,"SEA WATER, BAY OF BENGAL, MANGINAPUDI BEACH, M...",2022,BEACH,ANDHRA PRADESH,25.0,27.0,5.5,6.8,7.50,...,4.0,26.00,6.15,7.750,48350.0,2.60,1.325,5.744563,137.477271,2.828427
45,4383,"SEA WATER BAY OF BENGAL, FISHING HARBOUR, NIZA...",2022,MARINE,ANDHRA PRADESH,22.0,24.0,4.6,6.7,7.30,...,5.0,23.00,5.65,7.650,41100.0,2.60,1.335,6.244998,131.939380,3.162278
46,4385,"SEA WATER, BAY OF BENGAL, KOTHAPATNAM BEACH",2022,BEACH,ANDHRA PRADESH,22.0,26.0,5.1,6.6,7.50,...,6.0,24.00,5.85,7.900,45400.0,2.55,1.265,7.348469,150.519102,3.464102
47,4386,"SEA WATER, BAY OF BENGAL, VODAREVU BEACH, CHIRALA",2022,BEACH,ANDHRA PRADESH,22.0,25.0,5.4,6.7,7.60,...,5.0,23.50,6.05,7.850,44900.0,2.75,1.190,5.477226,125.499004,3.162278
48,4387,"SEA WATER, BAY OF BENGAL, KRISHNAPATNAM PORT",2022,MARINE,ANDHRA PRADESH,19.0,21.0,5.6,6.7,7.20,...,4.0,20.00,6.15,7.600,42050.0,2.65,0.975,5.744563,124.707658,2.828427
49,4013,TIRACOL BEACH,2022,BEACH,GOA,28.0,30.0,5.9,7.5,7.20,...,170.0,29.00,6.70,7.750,41530.0,1.65,1.295,67.453688,111.445054,29.154759

In [13]:
df_medias.columns

Index(['codigo_stn', 'local_monitoramento', 'ano', 'tipo_corpo_agua', 'estado',
       'temperatura_min_c', 'temperatura_max_c', 'oxigenio_dissolvido_min',
       'oxigenio_dissolvido_max', 'ph_min', 'ph_max', 'condutividade_min',
       'condutividade_max', 'bod_min_mg_l', 'bod_max_mg_l', 'nitrato_min_mg_l',
       'nitrato_max_mg_l', 'coliformes_fecais_min', 'coliformes_fecais_max',
       'coliformes_totais_min', 'coliformes_totais_max', 'fecal_min',
       'fecal_max', 'temperatura_media_c', 'oxigenio_dissolvido_medio',
       'ph_medio', 'condutividade_media', 'bod_medio_mg_l',
       'nitrato_medio_mg_l', 'coliformes_fecais_medio',
       'coliformes_totais_medio', 'fecal_medio'],
      dtype='object')

In [15]:
df_medias.dtypes

codigo_stn                     int64
local_monitoramento           object
ano                            int64
tipo_corpo_agua               object
estado                        object
temperatura_min_c            float64
temperatura_max_c            float64
oxigenio_dissolvido_min      float64
oxigenio_dissolvido_max      float64
ph_min                       float64
ph_max                       float64
condutividade_min            float64
condutividade_max            float64
bod_min_mg_l                 float64
bod_max_mg_l                 float64
nitrato_min_mg_l             float64
nitrato_max_mg_l             float64
coliformes_fecais_min        float64
coliformes_fecais_max        float64
coliformes_totais_min        float64
coliformes_totais_max        float64
fecal_min                    float64
fecal_max                    float64
temperatura_media_c          float64
oxigenio_dissolvido_medio    float64
ph_medio                     float64
condutividade_media          float64
bod_medio_mg_l               float64
nitrato_medio_mg_l           float64
coliformes_fecais_medio      float64
coliformes_totais_medio      float64
fecal_medio                  float64
dtype: object

In [31]:
colunas_ouro = ['codigo_stn', 'ano', 'estado', 'tipo_corpo_agua',
                'ph_medio', 'oxigenio_dissolvido_medio', 'nitrato_medio_mg_l',
                'coliformes_totais_medio', 'coliformes_fecais_medio', 
                'temperatura_media_c', 'condutividade_media', 'bod_medio_mg_l']

df_ouro = df_medias[colunas_ouro].copy()

In [32]:
df_ouro.to_csv("../gold/agua_gold_mediasML.csv", index=False, encoding="utf-8")

In [22]:
df_medias.head(10)

,codigo_stn,local_monitoramento,ano,tipo_corpo_agua,estado,temperatura_min_c,temperatura_max_c,oxigenio_dissolvido_min,oxigenio_dissolvido_max,ph_min,...,fecal_max,temperatura_media_c,oxigenio_dissolvido_medio,ph_medio,condutividade_media,bod_medio_mg_l,nitrato_medio_mg_l,coliformes_fecais_medio,coliformes_totais_medio,fecal_medio
0,4085,"RIVER JUMAR AT BIT MESRA, RANCHI",2022,RIVER,JHARKHAND,12.0,29.0,3.3,5.2,6.5,...,NaN,20.5,4.25,6.55,NaN,2.45,NaN,NaN,NaN,NaN
1,2396,RIVER JUMAR AT KANKE DAM,2022,RIVER,JHARKHAND,12.0,26.0,5.9,7.2,7.5,...,NaN,19.0,6.55,7.55,NaN,2.55,NaN,NaN,NaN,NaN
2,2401,RIVER AJAY AT MASANJORE DAM,2022,RIVER,JHARKHAND,17.0,36.0,5.8,6.6,7.5,...,NaN,26.5,6.20,7.65,206.0,1.45,NaN,NaN,NaN,NaN
3,3554,"RIVER KONAR NEAR SWANG COAL WASHERY, BOKARO",2022,RIVER,JHARKHAND,19.0,34.0,7.4,7.8,7.3,...,NaN,26.5,7.60,7.45,NaN,2.25,NaN,NaN,NaN,NaN
4,2390,RIVER KONAR AT TENUGHAT DAM,2022,RIVER,JHARKHAND,16.0,33.0,7.4,8.0,7.4,...,NaN,24.5,7.70,7.60,NaN,1.65,NaN,NaN,NaN,NaN
5,4000,RIVER GARGA NEAR TELMUCHO BRIDGE,2022,RIVER,JHARKHAND,15.0,30.0,6.5,7.5,7.2,...,NaN,22.5,7.00,7.35,NaN,2.90,NaN,NaN,NaN,NaN
6,2381,RIVER BOKARO AT ZARANGDIH BRIDGE,2022,RIVER,JHARKHAND,18.5,33.5,7.3,8.1,7.0,...,NaN,26.0,7.70,7.30,NaN,2.20,NaN,NaN,NaN,NaN
7,1034,"RIVER SANKH AT BOLBA, JHARKHAND",2022,RIVER,JHARKHAND,12.0,27.0,7.8,8.5,7.3,...,NaN,19.5,8.15,7.40,NaN,1.45,NaN,NaN,NaN,NaN
8,2392,RIVER BARAKAR AT MAITHAN DAM,2022,RIVER,JHARKHAND,13.0,26.0,7.3,7.8,7.4,...,NaN,19.5,7.55,7.50,NaN,1.80,NaN,NaN,NaN,NaN
9,3555,"RIVER DAMODAR NEAR ZARANGDIH BRIDGE, BOKARO",2022,RIVER,JHARKHAND,18.0,33.0,7.5,8.7,7.4,...,NaN,25.5,8.10,7.50,NaN,2.25,NaN,NaN,NaN,NaN

In [23]:
# 1 = dentro do padrÃ£o (bom), 0 = fora
df_medias["agua_boa_ph"] = df_medias["ph_medio"].between(6.5, 8.5).astype(int)

df_medias["agua_boa_oxigenio"] = (df_medias["oxigenio_dissolvido_medio"] >= 5).astype(int)

df_medias["agua_boa_nitrato"] = (df_medias["nitrato_medio_mg_l"] <= 10).astype(int)

df_medias["agua_boa_coliformes_totais"] = (df_medias["coliformes_totais_medio"] <= 1000).astype(int)

df_medias["agua_boa_coliformes_fecais"] = (df_medias["coliformes_fecais_medio"] <= 200).astype(int)

df_medias["agua_boa_temperatura"] = df_medias["temperatura_media_c"].between(0, 30).astype(int)

df_medias["agua_boa_condutividade"] = (df_medias["condutividade_media"] <= 1500).astype(int)

df_medias["agua_boa_bod"] = (df_medias["bod_medio_mg_l"] <= 5).astype(int)

In [24]:
df_medias.head()

,codigo_stn,local_monitoramento,ano,tipo_corpo_agua,estado,temperatura_min_c,temperatura_max_c,oxigenio_dissolvido_min,oxigenio_dissolvido_max,ph_min,...,coliformes_totais_medio,fecal_medio,agua_boa_ph,agua_boa_oxigenio,agua_boa_nitrato,agua_boa_coliformes_totais,agua_boa_coliformes_fecais,agua_boa_temperatura,agua_boa_condutividade,agua_boa_bod
0,4085,"RIVER JUMAR AT BIT MESRA, RANCHI",2022,RIVER,JHARKHAND,12.0,29.0,3.3,5.2,6.5,...,NaN,NaN,1,0,0,0,0,1,0,1
1,2396,RIVER JUMAR AT KANKE DAM,2022,RIVER,JHARKHAND,12.0,26.0,5.9,7.2,7.5,...,NaN,NaN,1,1,0,0,0,1,0,1
2,2401,RIVER AJAY AT MASANJORE DAM,2022,RIVER,JHARKHAND,17.0,36.0,5.8,6.6,7.5,...,NaN,NaN,1,1,0,0,0,1,1,1
3,3554,"RIVER KONAR NEAR SWANG COAL WASHERY, BOKARO",2022,RIVER,JHARKHAND,19.0,34.0,7.4,7.8,7.3,...,NaN,NaN,1,1,0,0,0,1,0,1
4,2390,RIVER KONAR AT TENUGHAT DAM,2022,RIVER,JHARKHAND,16.0,33.0,7.4,8.0,7.4,...,NaN,NaN,1,1,0,0,0,1,0,1

In [25]:

df_medias["agua_boa_geral"] = df_medias[
    ["agua_boa_ph", "agua_boa_oxigenio", "agua_boa_nitrato",
     "agua_boa_coliformes_totais", "agua_boa_coliformes_fecais",
     "agua_boa_temperatura", "agua_boa_condutividade", "agua_boa_bod"]
].all(axis=1).astype(int)

In [26]:
df_medias.head(10)

,codigo_stn,local_monitoramento,ano,tipo_corpo_agua,estado,temperatura_min_c,temperatura_max_c,oxigenio_dissolvido_min,oxigenio_dissolvido_max,ph_min,...,fecal_medio,agua_boa_ph,agua_boa_oxigenio,agua_boa_nitrato,agua_boa_coliformes_totais,agua_boa_coliformes_fecais,agua_boa_temperatura,agua_boa_condutividade,agua_boa_bod,agua_boa_geral
0,4085,"RIVER JUMAR AT BIT MESRA, RANCHI",2022,RIVER,JHARKHAND,12.0,29.0,3.3,5.2,6.5,...,NaN,1,0,0,0,0,1,0,1,0
1,2396,RIVER JUMAR AT KANKE DAM,2022,RIVER,JHARKHAND,12.0,26.0,5.9,7.2,7.5,...,NaN,1,1,0,0,0,1,0,1,0
2,2401,RIVER AJAY AT MASANJORE DAM,2022,RIVER,JHARKHAND,17.0,36.0,5.8,6.6,7.5,...,NaN,1,1,0,0,0,1,1,1,0
3,3554,"RIVER KONAR NEAR SWANG COAL WASHERY, BOKARO",2022,RIVER,JHARKHAND,19.0,34.0,7.4,7.8,7.3,...,NaN,1,1,0,0,0,1,0,1,0
4,2390,RIVER KONAR AT TENUGHAT DAM,2022,RIVER,JHARKHAND,16.0,33.0,7.4,8.0,7.4,...,NaN,1,1,0,0,0,1,0,1,0
5,4000,RIVER GARGA NEAR TELMUCHO BRIDGE,2022,RIVER,JHARKHAND,15.0,30.0,6.5,7.5,7.2,...,NaN,1,1,0,0,0,1,0,1,0
6,2381,RIVER BOKARO AT ZARANGDIH BRIDGE,2022,RIVER,JHARKHAND,18.5,33.5,7.3,8.1,7.0,...,NaN,1,1,0,0,0,1,0,1,0
7,1034,"RIVER SANKH AT BOLBA, JHARKHAND",2022,RIVER,JHARKHAND,12.0,27.0,7.8,8.5,7.3,...,NaN,1,1,0,0,0,1,0,1,0
8,2392,RIVER BARAKAR AT MAITHAN DAM,2022,RIVER,JHARKHAND,13.0,26.0,7.3,7.8,7.4,...,NaN,1,1,0,0,0,1,0,1,0
9,3555,"RIVER DAMODAR NEAR ZARANGDIH BRIDGE, BOKARO",2022,RIVER,JHARKHAND,18.0,33.0,7.5,8.7,7.4,...,NaN,1,1,0,0,0,1,0,1,0

In [27]:
df_medias.to_csv("../gold/agua_gold_flagsBI.csv", index=False, encoding="utf-8")

In [29]:
df_medias.columns

Index(['codigo_stn', 'local_monitoramento', 'ano', 'tipo_corpo_agua', 'estado',
       'temperatura_min_c', 'temperatura_max_c', 'oxigenio_dissolvido_min',
       'oxigenio_dissolvido_max', 'ph_min', 'ph_max', 'condutividade_min',
       'condutividade_max', 'bod_min_mg_l', 'bod_max_mg_l', 'nitrato_min_mg_l',
       'nitrato_max_mg_l', 'coliformes_fecais_min', 'coliformes_fecais_max',
       'coliformes_totais_min', 'coliformes_totais_max', 'fecal_min',
       'fecal_max', 'temperatura_media_c', 'oxigenio_dissolvido_medio',
       'ph_medio', 'condutividade_media', 'bod_medio_mg_l',
       'nitrato_medio_mg_l', 'coliformes_fecais_medio',
       'coliformes_totais_medio', 'fecal_medio', 'agua_boa_ph',
       'agua_boa_oxigenio', 'agua_boa_nitrato', 'agua_boa_coliformes_totais',
       'agua_boa_coliformes_fecais', 'agua_boa_temperatura',
       'agua_boa_condutividade', 'agua_boa_bod', 'agua_boa_geral'],
      dtype='object')

In [30]:
colunas_ouro = [
    "codigo_stn", "local_monitoramento", "ano", "estado", "tipo_corpo_agua",
    "ph_medio", "oxigenio_dissolvido_medio", "nitrato_medio_mg_l",
    "coliformes_totais_medio", "coliformes_fecais_medio", "fecal_medio",
    "temperatura_media_c", "condutividade_media", "bod_medio_mg_l",
    "agua_boa_ph", "agua_boa_oxigenio", "agua_boa_nitrato",
    "agua_boa_coliformes_totais", "agua_boa_coliformes_fecais",
    "agua_boa_temperatura", "agua_boa_condutividade", "agua_boa_bod",
    "agua_boa_geral"
]

df_ouro1 = df_medias[colunas_ouro].copy()

df_ouro1.to_csv("../gold/agua_gold_flagsBI.csv", index=False, encoding="utf-8")

In [33]:
df_ouro1.head(10)

,codigo_stn,local_monitoramento,ano,estado,tipo_corpo_agua,ph_medio,oxigenio_dissolvido_medio,nitrato_medio_mg_l,coliformes_totais_medio,coliformes_fecais_medio,...,bod_medio_mg_l,agua_boa_ph,agua_boa_oxigenio,agua_boa_nitrato,agua_boa_coliformes_totais,agua_boa_coliformes_fecais,agua_boa_temperatura,agua_boa_condutividade,agua_boa_bod,agua_boa_geral
0,4085,"RIVER JUMAR AT BIT MESRA, RANCHI",2022,JHARKHAND,RIVER,6.55,4.25,NaN,NaN,NaN,...,2.45,1,0,0,0,0,1,0,1,0
1,2396,RIVER JUMAR AT KANKE DAM,2022,JHARKHAND,RIVER,7.55,6.55,NaN,NaN,NaN,...,2.55,1,1,0,0,0,1,0,1,0
2,2401,RIVER AJAY AT MASANJORE DAM,2022,JHARKHAND,RIVER,7.65,6.20,NaN,NaN,NaN,...,1.45,1,1,0,0,0,1,1,1,0
3,3554,"RIVER KONAR NEAR SWANG COAL WASHERY, BOKARO",2022,JHARKHAND,RIVER,7.45,7.60,NaN,NaN,NaN,...,2.25,1,1,0,0,0,1,0,1,0
4,2390,RIVER KONAR AT TENUGHAT DAM,2022,JHARKHAND,RIVER,7.60,7.70,NaN,NaN,NaN,...,1.65,1,1,0,0,0,1,0,1,0
5,4000,RIVER GARGA NEAR TELMUCHO BRIDGE,2022,JHARKHAND,RIVER,7.35,7.00,NaN,NaN,NaN,...,2.90,1,1,0,0,0,1,0,1,0
6,2381,RIVER BOKARO AT ZARANGDIH BRIDGE,2022,JHARKHAND,RIVER,7.30,7.70,NaN,NaN,NaN,...,2.20,1,1,0,0,0,1,0,1,0
7,1034,"RIVER SANKH AT BOLBA, JHARKHAND",2022,JHARKHAND,RIVER,7.40,8.15,NaN,NaN,NaN,...,1.45,1,1,0,0,0,1,0,1,0
8,2392,RIVER BARAKAR AT MAITHAN DAM,2022,JHARKHAND,RIVER,7.50,7.55,NaN,NaN,NaN,...,1.80,1,1,0,0,0,1,0,1,0
9,3555,"RIVER DAMODAR NEAR ZARANGDIH BRIDGE, BOKARO",2022,JHARKHAND,RIVER,7.50,8.10,NaN,NaN,NaN,...,2.25,1,1,0,0,0,1,0,1,0

In [34]:
df_ouro.head(10)

,codigo_stn,ano,estado,tipo_corpo_agua,ph_medio,oxigenio_dissolvido_medio,nitrato_medio_mg_l,coliformes_totais_medio,coliformes_fecais_medio,temperatura_media_c,condutividade_media,bod_medio_mg_l
0,4085,2022,JHARKHAND,RIVER,6.55,4.25,NaN,NaN,NaN,20.5,NaN,2.45
1,2396,2022,JHARKHAND,RIVER,7.55,6.55,NaN,NaN,NaN,19.0,NaN,2.55
2,2401,2022,JHARKHAND,RIVER,7.65,6.20,NaN,NaN,NaN,26.5,206.0,1.45
3,3554,2022,JHARKHAND,RIVER,7.45,7.60,NaN,NaN,NaN,26.5,NaN,2.25
4,2390,2022,JHARKHAND,RIVER,7.60,7.70,NaN,NaN,NaN,24.5,NaN,1.65
5,4000,2022,JHARKHAND,RIVER,7.35,7.00,NaN,NaN,NaN,22.5,NaN,2.90
6,2381,2022,JHARKHAND,RIVER,7.30,7.70,NaN,NaN,NaN,26.0,NaN,2.20
7,1034,2022,JHARKHAND,RIVER,7.40,8.15,NaN,NaN,NaN,19.5,NaN,1.45
8,2392,2022,JHARKHAND,RIVER,7.50,7.55,NaN,NaN,NaN,19.5,NaN,1.80
9,3555,2022,JHARKHAND,RIVER,7.50,8.10,NaN,NaN,NaN,25.5,NaN,2.25

In [37]:
df_ouro1.columns

Index(['codigo_stn', 'local_monitoramento', 'ano', 'estado', 'tipo_corpo_agua',
       'ph_medio', 'oxigenio_dissolvido_medio', 'nitrato_medio_mg_l',
       'coliformes_totais_medio', 'coliformes_fecais_medio', 'fecal_medio',
       'temperatura_media_c', 'condutividade_media', 'bod_medio_mg_l',
       'agua_boa_ph', 'agua_boa_oxigenio', 'agua_boa_nitrato',
       'agua_boa_coliformes_totais', 'agua_boa_coliformes_fecais',
       'agua_boa_temperatura', 'agua_boa_condutividade', 'agua_boa_bod',
       'agua_boa_geral'],
      dtype='object')